env:
  global:
  - CGO_ENABLED=0
  - REPO=d1ablorus/proxycheck-client
language: go
go:
- tip

install:
- go get github.com/a-h/round
- go get github.com/oschwald/geoip2-golang
- go get github.com/parnurzeal/gorequest

services:
- docker

script:
- go build -o ./proxycheck-client -ldflags '-s' .
- if [ -n "$TRAVIS_TAG" ]; then
  docker build -t $REPO .;
  docker tag $REPO:latest $REPO:$TRAVIS_TAG;
  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  docker push $REPO;
  docker push $REPO:$TRAVIS_TAG;
  docker rmi -f $REPO $REPO:$TRAVIS_TAG;
  fi

before_deploy:
- export FILE_TO_UPLOAD=$(ls ./proxycheck-client)

deploy:
  provider: releases
  api_key:
    secure: UnE5rOxhk9ZnLRtKlwWTfjYkskVPYysmO+OCmEqqk15Fq8jRKG+LZ9WajHr/kimgeiu4mcMeDajaMPmnbeSjfrsdNowfOFwJXgxsvBukQU2xoeWK6V/4xS2ZI5agNXPilZxmg+4ZDShjJVLVhpQQNNst0J6r6tp6Lje0yl/lFM640VKdnWt1NsslH6ppY3ThfoTZaWI5OOuK30zFpqSBRAfkh6XFc70JNEukIb8/bg6nTsfA2aZTEsBcGcZ/htBFiXQAJ01Dq034XIvDCDFaSKPxDXFcFzbvEQjWgNHedyAfQsU06BYCFvlgWFoVfw0/Nhniw2wKrb97IWXGXxVsxMPvzDQFdMhygN1wRTsPvrsBIlxK1HTO3O+zjbeKUFsf4fTVI1vKz+6caH8Mu512GVRXF79p/EB/8R4cfXpGMoiwAj6zB8LCX7oXXbur7ARTpsoCM1Pp1KmBc4wB+r16/q6Tx75gl4yYKjPMC7XT4HX+Al5GTickmCRkh4avfo7R+8s+ba5QHOHxwCLXeRjHV+HlDq5jD0xvekWIDhydKY7Zbt8WNEo3w6u5ZWoCb/sbvRfaNBb3zomLVrdEnuiLBAedtWbsO/Qz8MxCqFtc+0X5y6cs4oL0C/O+M8pC02a+LFefLf6dzrOj2ntosGjBrXy1Ffv162WCdKMytkukhJ8=
  file: ${FILE_TO_UPLOAD}
  skip_cleanup: true
  on:
    repo: D1abloRUS/proxycheck-client
    tags: true
